import React from 'react';

// Sample QR Data options to simulate scanning
// Added serial_number to simulate unique box IDs generated by Admin
export const MOCK_QR_OPTIONS = [
  {
    label: "Amoxicillin (Box #101)",
    data: {
      "drug_id": "ABX-GEN-001",
      "serial_number": "SN-AMX-2024-001",
      "name": "Amoxicillin",
      "dosage": "500mg",
      "frequency_per_day": 3,
      "duration_days": 5,
      "instruction": "After food",
      "total_pills": 15,
      "exp_date": "2025-12-31",
      "how_to_take": "Swallow whole with water",
      "how_to_dispose": "Return to pharmacy",
      "side_effects": "May cause drowsiness"
    }
  },
  {
    label: "Azithromycin (Box #552)",
    data: {
      "drug_id": "ABX-GEN-002",
      "serial_number": "SN-AZI-2024-552",
      "name": "Azithromycin",
      "dosage": "500mg",
      "frequency_per_day": 1,
      "duration_days": 3,
      "instruction": "Before food",
      "total_pills": 3,
      "exp_date": "2025-06-30"
    }
  },
  {
    label: "Ciprofloxacin (Box #889)",
    data: {
      "drug_id": "ABX-GEN-003",
      "serial_number": "SN-CIP-2024-889",
      "name": "Ciprofloxacin",
      "dosage": "250mg",
      "frequency_per_day": 2,
      "duration_days": 7,
      "instruction": "After food",
      "total_pills": 14,
      "exp_date": "2025-10-15"
    }
  }
];

export const COLORS = {
  primary: '#0ea5e9', // Sky 500
  success: '#22c55e', // Green 500
  warning: '#eab308', // Yellow 500
  danger: '#ef4444', // Red 500
  background: '#f8fafc', // Slate 50
};