
export interface DrugQRCodeData {
  drug_id: string; // Generic ID (e.g., SKU)
  serial_number: string; // Unique ID per box/QR (generated by Admin)
  name: string;
  dosage: string;
  frequency_per_day: number;
  duration_days: number;
  instruction: string;
  total_pills: number;
  exp_date?: string; // ISO Date String
}

export interface Drug extends DrugQRCodeData {
  id: string; // Internal App UUID
  startDate: string; // ISO String
  isActive: boolean;
}

export type DoseStatus = 'pending' | 'taken' | 'missed' | 'skipped';

export interface Dose {
  id: string;
  drugId: string;
  drugName: string;
  scheduledTime: string; // ISO String
  status: DoseStatus;
  takenTime?: string; // ISO String
  pillNumber: number; // e.g., Dose 1 of 15
  totalPills: number;
  notificationSent?: boolean; // New flag to prevent spamming
}

export interface DailyStats {
  date: string;
  taken: number;
  total: number;
}

export interface User {
  name: string;
  email?: string;
  birthDate?: string;
  type: 'standard' | 'elderly';
  id: string;
}